#pragma once

namespace EngineCore
{
	enum PERF_CPU
	{
		PERF_CPU_FRAME,
		PERF_CPU_LUA_TICK,
		PERF_CPU_WIN_MSG,
		PERF_CPU_GUI_UPDATE,
		PERF_CPU_SCENE,
		PERF_CPU_SCENE_UPDATE,
		PERF_CPU_SCENE_DRAW,
		PERF_CPU_GUI_DRAW,
		PERF_CPU_PRESENT,

		PERF_CPU_COUNT,
	};

	enum PERF_GPU
	{
		PERF_GPU_FRAME,
		PERF_GPU_SCENE,
		PERF_GPU_SCENE_SHADOWS,
		PERF_GPU_SCENE_FORWARD,
		PERF_GPU_SCENE_DEFFERED,
		PERF_GPU_GUI,
		PERF_GPU_PRESENT,

		PERF_GPU_COUNT,
	};
}
