#pragma once

#include "Common.h"

#define LIGHT_SPOT_FRAME_MAX 128
#define LIGHT_SPOT_DISK_FRAME_MAX 128
#define LIGHT_SPOT_RECT_FRAME_MAX 128
#define LIGHT_POINT_FRAME_MAX 128
#define LIGHT_POINT_SPHERE_FRAME_MAX 128
#define LIGHT_POINT_TUBE_FRAME_MAX 128
#define LIGHT_DIR_FRAME_MAX 8
#define LIGHT_DIR_NUM_CASCADES 4

#define CASTER_SPOT_FRAME_MAX 64
#define CASTER_SPOT_DISK_FRAME_MAX 64
#define CASTER_SPOT_RECT_FRAME_MAX 64
#define CASTER_POINT_FRAME_MAX 32
#define CASTER_POINT_SPHERE_FRAME_MAX 32
#define CASTER_POINT_TUBE_FRAME_MAX 32

namespace EngineCore
{
	struct SpotLightBuffer
	{
		XMFLOAT4 Pos_Range[LIGHT_SPOT_FRAME_MAX];
		XMFLOAT4 Color_ConeX[LIGHT_SPOT_FRAME_MAX];
		XMFLOAT4 Dir_ConeY[LIGHT_SPOT_FRAME_MAX];
	};

	struct SpotCasterBuffer
	{
		XMFLOAT4 Pos_Range[CASTER_SPOT_FRAME_MAX];
		XMFLOAT4 Color_ConeX[CASTER_SPOT_FRAME_MAX];
		XMFLOAT4 Dir_ConeY[CASTER_SPOT_FRAME_MAX];
		XMFLOAT4 ShadowmapAdress[CASTER_SPOT_FRAME_MAX];
		XMFLOAT4 ShadowmapParams[CASTER_SPOT_FRAME_MAX];
		XMMATRIX ViewProj[CASTER_SPOT_FRAME_MAX];
	};

	struct SpotLightDiskBuffer
	{
		XMFLOAT4 Pos_Range[LIGHT_SPOT_DISK_FRAME_MAX];
		XMFLOAT4 Color_ConeX[LIGHT_SPOT_DISK_FRAME_MAX];
		XMFLOAT4 Dir_ConeY[LIGHT_SPOT_DISK_FRAME_MAX];
		XMFLOAT4 AreaInfo_Empty[LIGHT_SPOT_DISK_FRAME_MAX];
		XMFLOAT4 Virtpos_Empty[LIGHT_SPOT_DISK_FRAME_MAX];
	};

	struct SpotCasterDiskBuffer
	{
		XMFLOAT4 Pos_Range[CASTER_SPOT_DISK_FRAME_MAX];
		XMFLOAT4 Color_ConeX[CASTER_SPOT_DISK_FRAME_MAX];
		XMFLOAT4 Dir_ConeY[CASTER_SPOT_DISK_FRAME_MAX];
		XMFLOAT4 AreaInfo_Empty[CASTER_SPOT_DISK_FRAME_MAX];
		XMFLOAT4 Virtpos_Empty[CASTER_SPOT_DISK_FRAME_MAX];
		XMFLOAT4 ShadowmapAdress[CASTER_SPOT_DISK_FRAME_MAX];
		XMFLOAT4 ShadowmapParams[CASTER_SPOT_DISK_FRAME_MAX];
		XMMATRIX ViewProj[CASTER_SPOT_DISK_FRAME_MAX];
	};
	
	struct SpotLightRectBuffer
	{
		XMFLOAT4 Pos_Range[LIGHT_SPOT_RECT_FRAME_MAX];
		XMFLOAT4 Color_ConeX[LIGHT_SPOT_RECT_FRAME_MAX];
		XMFLOAT4 Dir_ConeY[LIGHT_SPOT_RECT_FRAME_MAX];
		XMFLOAT4 DirUp_AreaX[LIGHT_SPOT_RECT_FRAME_MAX];
		XMFLOAT4 DirSide_AreaY[LIGHT_SPOT_RECT_FRAME_MAX];
		XMFLOAT4 Virtpos_AreaZ[LIGHT_SPOT_RECT_FRAME_MAX];
	};

	struct SpotCasterRectBuffer
	{
		XMFLOAT4 Pos_Range[CASTER_SPOT_RECT_FRAME_MAX];
		XMFLOAT4 Color_ConeX[CASTER_SPOT_RECT_FRAME_MAX];
		XMFLOAT4 Dir_ConeY[CASTER_SPOT_RECT_FRAME_MAX];
		XMFLOAT4 DirUp_AreaX[CASTER_SPOT_RECT_FRAME_MAX];
		XMFLOAT4 DirSide_AreaY[CASTER_SPOT_RECT_FRAME_MAX];
		XMFLOAT4 Virtpos_AreaZ[CASTER_SPOT_RECT_FRAME_MAX];
		XMFLOAT4 ShadowmapAdress[CASTER_SPOT_RECT_FRAME_MAX];
		XMFLOAT4 ShadowmapParams[CASTER_SPOT_RECT_FRAME_MAX];
		XMMATRIX ViewProj[CASTER_SPOT_RECT_FRAME_MAX];
	};

	struct PointLightBuffer
	{
		XMFLOAT4 Pos_Range[LIGHT_POINT_FRAME_MAX];
		XMFLOAT4 Color[LIGHT_POINT_FRAME_MAX];
	};

	struct PointCasterBuffer
	{
		XMFLOAT4 Pos_Range[CASTER_POINT_FRAME_MAX];
		XMFLOAT4 Color_ShParams[CASTER_POINT_FRAME_MAX];
		XMFLOAT4 ShadowmapParams0[CASTER_POINT_FRAME_MAX];
		XMFLOAT4 ShadowmapParams1[CASTER_POINT_FRAME_MAX];
		XMMATRIX Proj[CASTER_POINT_FRAME_MAX];
		XMFLOAT4 ShadowmapAdress0[CASTER_POINT_FRAME_MAX];
		XMFLOAT4 ShadowmapAdress1[CASTER_POINT_FRAME_MAX];
		XMFLOAT4 ShadowmapAdress2[CASTER_POINT_FRAME_MAX];
		XMFLOAT4 ShadowmapAdress3[CASTER_POINT_FRAME_MAX];
		XMFLOAT4 ShadowmapAdress4[CASTER_POINT_FRAME_MAX];
		XMFLOAT4 ShadowmapAdress5[CASTER_POINT_FRAME_MAX];
	};

	struct PointLightSphereBuffer
	{
		XMFLOAT4 Pos_Range[LIGHT_POINT_SPHERE_FRAME_MAX];
		XMFLOAT4 Color_Empty[LIGHT_POINT_SPHERE_FRAME_MAX];
		XMFLOAT4 AreaInfo_Empty[LIGHT_POINT_SPHERE_FRAME_MAX];
	};

	struct PointCasterSphereBuffer
	{
		XMFLOAT4 Pos_Range[CASTER_POINT_SPHERE_FRAME_MAX];
		XMFLOAT4 Color_ShParams[CASTER_POINT_SPHERE_FRAME_MAX];
		XMFLOAT4 AreaInfo_ShParams[CASTER_POINT_SPHERE_FRAME_MAX];
		XMFLOAT4 ShadowmapParams[CASTER_POINT_SPHERE_FRAME_MAX];
		XMMATRIX Proj[CASTER_POINT_SPHERE_FRAME_MAX];
		XMFLOAT4 ShadowmapAdress0[CASTER_POINT_SPHERE_FRAME_MAX];
		XMFLOAT4 ShadowmapAdress1[CASTER_POINT_SPHERE_FRAME_MAX];
		XMFLOAT4 ShadowmapAdress2[CASTER_POINT_SPHERE_FRAME_MAX];
		XMFLOAT4 ShadowmapAdress3[CASTER_POINT_SPHERE_FRAME_MAX];
		XMFLOAT4 ShadowmapAdress4[CASTER_POINT_SPHERE_FRAME_MAX];
		XMFLOAT4 ShadowmapAdress5[CASTER_POINT_SPHERE_FRAME_MAX];
	};

	struct PointLightTubeBuffer
	{
		XMFLOAT4 Pos_Range[LIGHT_POINT_TUBE_FRAME_MAX];
		XMFLOAT4 Color_Empty[LIGHT_POINT_TUBE_FRAME_MAX];
		XMFLOAT4 AreaInfo[LIGHT_POINT_TUBE_FRAME_MAX];
		XMFLOAT4 Dir_AreaA[LIGHT_POINT_TUBE_FRAME_MAX];
	};
	
	struct PointCasterTubeBuffer
	{
		XMFLOAT4 Pos_Range[CASTER_POINT_TUBE_FRAME_MAX];
		XMFLOAT4 Color_ShParams[CASTER_POINT_TUBE_FRAME_MAX];
		XMFLOAT4 AreaInfo[CASTER_POINT_TUBE_FRAME_MAX];
		XMFLOAT4 Dir_AreaA[CASTER_POINT_TUBE_FRAME_MAX];
		XMFLOAT4 ShadowmapParams0[CASTER_POINT_TUBE_FRAME_MAX];
		XMFLOAT4 ShadowmapParams1[CASTER_POINT_TUBE_FRAME_MAX];
		XMMATRIX Proj[CASTER_POINT_TUBE_FRAME_MAX];
		XMMATRIX View[CASTER_POINT_TUBE_FRAME_MAX];
		XMFLOAT4 ShadowmapAdress0[CASTER_POINT_TUBE_FRAME_MAX];
		XMFLOAT4 ShadowmapAdress1[CASTER_POINT_TUBE_FRAME_MAX];
		XMFLOAT4 ShadowmapAdress2[CASTER_POINT_TUBE_FRAME_MAX];
		XMFLOAT4 ShadowmapAdress3[CASTER_POINT_TUBE_FRAME_MAX];
		XMFLOAT4 ShadowmapAdress4[CASTER_POINT_TUBE_FRAME_MAX];
		XMFLOAT4 ShadowmapAdress5[CASTER_POINT_TUBE_FRAME_MAX];
	};

	struct DirLightBuffer
	{
		XMFLOAT4 Color_AreaX[LIGHT_DIR_FRAME_MAX];
		XMFLOAT4 Dir_AreaY[LIGHT_DIR_FRAME_MAX];
		XMFLOAT4 Pos0[LIGHT_DIR_FRAME_MAX];
		XMFLOAT4 Pos1[LIGHT_DIR_FRAME_MAX];
		XMFLOAT4 Pos2[LIGHT_DIR_FRAME_MAX];
		XMFLOAT4 Pos3[LIGHT_DIR_FRAME_MAX];
		XMMATRIX ViewProj0[LIGHT_DIR_FRAME_MAX];
		XMMATRIX ViewProj1[LIGHT_DIR_FRAME_MAX];
		XMMATRIX ViewProj2[LIGHT_DIR_FRAME_MAX];
		XMMATRIX ViewProj3[LIGHT_DIR_FRAME_MAX];
		XMFLOAT4 ShadowmapAdress0[LIGHT_DIR_FRAME_MAX];
		XMFLOAT4 ShadowmapAdress1[LIGHT_DIR_FRAME_MAX];
		XMFLOAT4 ShadowmapAdress2[LIGHT_DIR_FRAME_MAX];
		XMFLOAT4 ShadowmapAdress3[LIGHT_DIR_FRAME_MAX];
	};
}