#pragma once

namespace EngineCore
{
	enum PERF_CPU
	{
		PERF_CPU_FRAME,
		PERF_CPU_LUA_TICK,
		PERF_CPU_WIN_MSG,
		PERF_CPU_GUI_UPDATE,
		PERF_CPU_SCENE,
		PERF_CPU_SCENE_UPDATE,
		PERF_CPU_SCENE_DRAW,
		
		PERF_CPU_VOXELIZATION,
		PERF_CPU_VOXELLIGHT,

		PERF_CPU_GUI_DRAW,
		PERF_CPU_PRESENT,

		PERF_CPU_COUNT,
	};

	enum PERF_GPU
	{
		PERF_GPU_FRAME,
		PERF_GPU_SCENE,
		PERF_GPU_SCENE_SHADOWS,
		PERF_GPU_SCENE_FORWARD,

		PERF_GPU_VOXELIZATION,

		PERF_GPU_VOXELLIGHT,
		PERF_GPU_LIGHTINJECT,
		PERF_GPU_VOXELDOWNSAMPLE,

		PERF_GPU_GEOMETRY,
		PERF_GPU_DEPTH_COPY,
		
		PERF_GPU_SCENE_DEFFERED,

		PERF_GPU_HIZ_GEN,
		PERF_GPU_SSR,
		PERF_GPU_AO,
		PERF_GPU_OPAQUE_MAIN,
		PERF_GPU_OPAQUE_FINAL,
		PERF_GPU_HDR_BLOOM,

		PERF_GPU_SCENE_APLHA,
		PERF_GPU_SCENE_LDR,

		PERF_GPU_SCENE_UI,

		PERF_GPU_COMBINE,
		PERF_GPU_AA,

		PERF_GPU_GUI,
		PERF_GPU_PRESENT,

		PERF_GPU_COUNT,
	};
}
