
PreloadList = {
    { PATH.FONTS .."opensans_light_18px", RESOURCE_TYPE.FONT },
    { PATH.FONTS .."opensans_light_20px", RESOURCE_TYPE.FONT },
    { PATH.FONTS .."opensans_light_25px", RESOURCE_TYPE.FONT },
    { PATH.FONTS .."opensans_light_40px", RESOURCE_TYPE.FONT },
    { PATH.FONTS .."opensans_light_70px", RESOURCE_TYPE.FONT },
    { PATH.FONTS .."opensans_normal_12px", RESOURCE_TYPE.FONT },
    { PATH.FONTS .."opensans_normal_14px", RESOURCE_TYPE.FONT },
    { PATH.FONTS .."opensans_normal_16px", RESOURCE_TYPE.FONT },
    { PATH.FONTS .."opensans_normal_18px", RESOURCE_TYPE.FONT },
    { PATH.FONTS .."opensans_normal_20px", RESOURCE_TYPE.FONT },
    { PATH.FONTS .."opensans_normal_25px", RESOURCE_TYPE.FONT },
    { PATH.FONTS .."opensans_normal_40px", RESOURCE_TYPE.FONT },
    { PATH.FONTS .."opensans_normal_70px", RESOURCE_TYPE.FONT },

    { PATH.SYS_TEXTURES .."noise2d".. EXT.TEXTURE, RESOURCE_TYPE.TEXTURE },
    { PATH.SYS_TEXTURES .."pbs_env_lut".. EXT.TEXTURE, RESOURCE_TYPE.TEXTURE },
    { PATH.SYS_TEXTURES .."aa/smaa_area".. EXT.TEXTURE, RESOURCE_TYPE.TEXTURE },
    { PATH.SYS_TEXTURES .."aa/smaa_search".. EXT.TEXTURE, RESOURCE_TYPE.TEXTURE },
    { PATH.SYS_TEXTURES .."hbaoDither".. EXT.TEXTURE, RESOURCE_TYPE.TEXTURE },
    { PATH.SYS_TEXTURES .."hammersley".. EXT.TEXTURE, RESOURCE_TYPE.TEXTURE },

    { PATH.SYS_TEXTURES .."editor_hud/arrow_down".. EXT.TEXTURE, RESOURCE_TYPE.TEXTURE },
    { PATH.SYS_TEXTURES .."editor_hud/arrow_right".. EXT.TEXTURE, RESOURCE_TYPE.TEXTURE },
    { PATH.SYS_TEXTURES .."editor_hud/maximize".. EXT.TEXTURE, RESOURCE_TYPE.TEXTURE },
    { PATH.SYS_TEXTURES .."editor_hud/minimize".. EXT.TEXTURE, RESOURCE_TYPE.TEXTURE },
    { PATH.SYS_TEXTURES .."editor_hud/move".. EXT.TEXTURE, RESOURCE_TYPE.TEXTURE },
    { PATH.SYS_TEXTURES .."editor_hud/pipet".. EXT.TEXTURE, RESOURCE_TYPE.TEXTURE },
    { PATH.SYS_TEXTURES .."editor_hud/reset".. EXT.TEXTURE, RESOURCE_TYPE.TEXTURE },
    { PATH.SYS_TEXTURES .."editor_hud/restore".. EXT.TEXTURE, RESOURCE_TYPE.TEXTURE },
    { PATH.SYS_TEXTURES .."editor_hud/rotate".. EXT.TEXTURE, RESOURCE_TYPE.TEXTURE },
    { PATH.SYS_TEXTURES .."editor_hud/scale".. EXT.TEXTURE, RESOURCE_TYPE.TEXTURE },
    { PATH.SYS_TEXTURES .."editor_hud/select".. EXT.TEXTURE, RESOURCE_TYPE.TEXTURE },
    { PATH.SYS_TEXTURES .."editor_hud/win_close".. EXT.TEXTURE, RESOURCE_TYPE.TEXTURE },
    { PATH.SYS_TEXTURES .."editor_hud/assign_asset".. EXT.TEXTURE, RESOURCE_TYPE.TEXTURE },
    { PATH.SYS_TEXTURES .."editor_hud/clear_str".. EXT.TEXTURE, RESOURCE_TYPE.TEXTURE },
    { PATH.SYS_TEXTURES .."editor_hud/delete".. EXT.TEXTURE, RESOURCE_TYPE.TEXTURE },
    { PATH.SYS_TEXTURES .."editor_hud/copy_mat".. EXT.TEXTURE, RESOURCE_TYPE.TEXTURE },
    { PATH.SYS_TEXTURES .."editor_hud/new_mat".. EXT.TEXTURE, RESOURCE_TYPE.TEXTURE },

    { PATH.SYS_MESHES .."sky_shpere".. EXT.MESH, RESOURCE_TYPE.MESH },
    { PATH.SYS_MESHES .."mat_sphere".. EXT.MESH, RESOURCE_TYPE.MESH },

    { PATH.SHADERS .."objects/editor/line_geometry", RESOURCE_TYPE.SHADER },
    { PATH.SHADERS .."objects/editor/line_geometry_sphere", RESOURCE_TYPE.SHADER },
    { PATH.SHADERS .."objects/opaque_main", RESOURCE_TYPE.SHADER },
    { PATH.SHADERS .."objects/alphatest_main", RESOURCE_TYPE.SHADER },
    --{ PATH.SHADERS .."objects/transparent_medium", RESOURCE_TYPE.SHADER },

    { PATH.SHADERS .."system/depth_copy_hiz", RESOURCE_TYPE.GUI_SHADER },
    { PATH.SHADERS .."system/hbao", RESOURCE_TYPE.GUI_SHADER },
    { PATH.SHADERS .."system/hbao_perspective_correct", RESOURCE_TYPE.GUI_SHADER },
    { PATH.SHADERS .."system/hdr", RESOURCE_TYPE.GUI_SHADER },
    { PATH.SHADERS .."system/hiz_depth", RESOURCE_TYPE.GUI_SHADER },
    { PATH.SHADERS .."system/opaque_blur", RESOURCE_TYPE.GUI_SHADER },
    { PATH.SHADERS .."system/avglum", RESOURCE_TYPE.GUI_SHADER },
    { PATH.SHADERS .."system/bloom_find", RESOURCE_TYPE.GUI_SHADER },
    { PATH.SHADERS .."system/aa_edge", RESOURCE_TYPE.GUI_SHADER },
    { PATH.SHADERS .."system/aa_blend", RESOURCE_TYPE.GUI_SHADER },
    { PATH.SHADERS .."system/aa_final", RESOURCE_TYPE.GUI_SHADER },

    { PATH.SHADERS .."system/scene_to_color_alpha", RESOURCE_TYPE.GUI_SHADER },
    { PATH.SHADERS .."offline/envmap_mipgen", RESOURCE_TYPE.GUI_SHADER },
    { PATH.SHADERS .."offline/envmap_mipcopy", RESOURCE_TYPE.GUI_SHADER },
    { PATH.SHADERS .."offline/scep_diff_dfg", RESOURCE_TYPE.GUI_SHADER },
    { PATH.SHADERS .."offline/noise2d", RESOURCE_TYPE.GUI_SHADER },

    { PATH.SHADERS .."gui/color", RESOURCE_TYPE.GUI_SHADER },
    { PATH.SHADERS .."gui/font_default", RESOURCE_TYPE.GUI_SHADER },
    { PATH.SHADERS .."gui/group_arrow", RESOURCE_TYPE.GUI_SHADER },
    { PATH.SHADERS .."gui/h_picker", RESOURCE_TYPE.GUI_SHADER },
    { PATH.SHADERS .."gui/rect", RESOURCE_TYPE.GUI_SHADER },
    { PATH.SHADERS .."gui/rect_icon", RESOURCE_TYPE.GUI_SHADER },
    { PATH.SHADERS .."gui/rect_color_icon_alpha", RESOURCE_TYPE.GUI_SHADER },
    { PATH.SHADERS .."gui/rect_icon_bg", RESOURCE_TYPE.GUI_SHADER },
    { PATH.SHADERS .."gui/shadow", RESOURCE_TYPE.GUI_SHADER },
    { PATH.SHADERS .."gui/sv_picker", RESOURCE_TYPE.GUI_SHADER },
    { PATH.SHADERS .."gui/t_picker", RESOURCE_TYPE.GUI_SHADER },
    { PATH.SHADERS .."gui/viewport", RESOURCE_TYPE.GUI_SHADER },
    { PATH.SHADERS .."gui/viewport_2darr", RESOURCE_TYPE.GUI_SHADER },
    { PATH.SHADERS .."gui/viewport_cube", RESOURCE_TYPE.GUI_SHADER },
	
	{ PATH.SHADERS .."system/deffered_opaque_simple#DefferedLightingIBL#", RESOURCE_TYPE.COMPUTE },
    { PATH.SHADERS .."system/deffered_opaque#DefferedLighting#", RESOURCE_TYPE.COMPUTE },
	{ PATH.SHADERS .. "offline/prob_capture#Capture#", RESOURCE_TYPE.COMPUTE },
	{ PATH.SHADERS .. "system/combine#Combine#", RESOURCE_TYPE.COMPUTE },
}

function PreloadList:PreloadResources()
    for i = 1, #self do
        Resource.PreloadResource( self[i][1], self[i][2] )
    end
    Resource.WaitLoadingComplete()
end
